spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:C:\Users\Admin\Documents\ADA\POSTGRES SQL-NUEVO\ejemplo del cuadro\postgressql2
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect